
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpassfile:/pgadmin4/pgpassfile
    depends_on:
      - postgres

  spark-etl:
    build: .
    container_name: spark-etl
    volumes:
      - ./data:/app/data
    environment:
      - SPARK_HOME=/opt/spark
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=etl_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    command: ["python", "-m", "pyspark_etl_project.etl"]

volumes:
  postgres_data: