global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "airflow"
    metrics_path: /admin/metrics
    static_configs:
      - targets: ["airflow:8080"]

  - job_name: "spark"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["spark-etl:4040"]
    
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"] 